### ISSUE TITLE
Space-adapted and grav-adapted humans are listed as a subtype of vat grown

### ISSUE THREAD

**Issue by PurpleMartinJCK** [Baystation12/Baystation12-Lore#35]
I was reading the lore wiki and in this section https://baystation12.net/lore/Section%202 scroll down to vat-grown humans. It says "From this baseline version, there are two other variants." and then goes on to list space-adapted and grav-adapted.

This, however isn't true https://github.com/Baystation12/Baystation12/issues/13994#issuecomment-241667922 and should be fixed.

**Comment by Raptor1628** [comment]
Human subspecies are gene modded, but aren't able to have the same kind of "series-built" background as vat grown, sooo...closing this in preparation for transhuman lore.
