### ISSUE TITLE
A'sranda page not existing

### ISSUE THREAD

**Issue by ThatOneGuy42** [Baystation12/Baystation12-Lore#46]
Despite the page existing in the files, it doesn't show up on the actual site, nor in the Files view, but Saveel does.

**Comment by GinjaNinja32** [comment]
Sounds like an apostrophe bug. Maybe call it Asranda but clarify at the top of the page that it's supposed to be A'sranda?

**Comment by ThatOneGuy42** [comment]
Fixed, thanks
